#!/usr/bin/env python3
"""
Ryoku-WE

Unified Ryoku wallpaper support + TUI.

Validated routing:
  Pictures / stills        -> native Ryoku
  Local GIFs               -> native Ryoku + AnimatedImage patch
  Local videos             -> native Ryoku
  Steam Workshop videos    -> native Ryoku
  Wallpaper Engine scenes  -> we-layerd
  Wallpaper audio          -> global mute/unmute toggle

Run with no arguments to open the TUI.

CLI commands (also used internally by systemd):
  install
  repair
  status
  sync
  index
  gif-patch
  mute
  unmute
  toggle-mute
  restart-we
  picker
  logo
  uninstall
"""

from __future__ import annotations

import argparse
import contextlib
import curses
import io
import json
import os
import re
import shutil
import signal
import subprocess
import sys
import textwrap
import time
from datetime import datetime
from pathlib import Path

APP_NAME = "Ryoku-WE"
VERSION = "2.4.2"

LOGO_ROWS = (
    (('0D0D0D', '11'), ('0E0E0E', '01'), ('0E0E0D', '0'), ('0E0E0E', '01'), ('0F0F0F', '0'), ('101010', '1'), ('111111', '01'), ('121212', '0'), ('131313', '11'), ('141414', '1'), ('151515', '1010010001'), ('161616', '11011'), ('151515', '0'), ('161615', '01'), ('151515', '0'), ('141515', '1'), ('141414', '0'), ('131313', '0'), ('121212', '00'), ('111111', '00000'), ('101010', '100100')),
    (('0D0D0D', '00'), ('0D0E0D', '0'), ('0E0E0E', '1'), ('0E0E0D', '0'), ('0E0E0E', '0'), ('0F0F0F', '0'), ('111111', '1'), ('131313', '0'), ('151515', '0'), ('161615', '0'), ('171716', '1'), ('181818', '1'), ('1A1A1A', '0'), ('1A1B1B', '0'), ('1B1B1B', '0'), ('1C1C1C', '110'), ('1B1B1B', '10100'), ('1C1C1C', '1'), ('1D1D1D', '100'), ('1C1C1C', '10'), ('1D1D1D', '1'), ('1D1D1C', '0'), ('1E1E1E', '1'), ('1D1D1D', '1'), ('1B1B1B', '1'), ('1A1A1A', '1'), ('181819', '1'), ('161616', '1'), ('141414', '1'), ('131313', '1111'), ('121212', '10'), ('111112', '1'), ('111111', '1100')),
    (('0D0D0D', '001'), ('0E0E0E', '0'), ('0F0F0F', '1'), ('101010', '1'), ('131313', '0'), ('161616', '1'), ('181918', '0'), ('212121', '0'), ('383838', '0'), ('4B4C4B', '1'), ('515151', '1'), ('545454', '0'), ('565656', '1'), ('585857', '1'), ('595958', '0'), ('5A5B59', '1'), ('595958', '00111'), ('585857', '1'), ('595958', '0'), ('595A59', '0'), ('595B5A', '0'), ('595A5A', '1'), ('595959', '10'), ('5A5A5A', '0'), ('5B5B5B', '1'), ('5D5E5E', '0'), ('676766', '1'), ('5F5F5E', '1'), ('444443', '1'), ('282829', '0'), ('1E1F1F', '0'), ('1A1B1B', '1'), ('171717', '0'), ('151615', '1'), ('151515', '1'), ('151414', '0'), ('141415', '1'), ('141414', '10'), ('131313', '01'), ('131312', '1'), ('121213', '1')),
    (('0C0C0C', '1'), ('0D0D0D', '0'), ('0E0E0E', '0'), ('0F0F0F', '1'), ('111111', '0'), ('171716', '0'), ('1F1F1F', '1'), ('2F2F2F', '0'), ('5F605F', '0'), ('606160', '0'), ('737372', '0'), ('A8A8A7', '0'), ('B0B0AF', '1'), ('B5B5B5', '0'), ('B6B6B5', '1'), ('B8B8B7', '1'), ('B9B9B8', '0'), ('BABAB8', '0'), ('BABBB9', '1'), ('B9BAB8', '0'), ('B7B7B6', '0'), ('B7B7B5', '1'), ('B6B6B5', '01'), ('B7B7B6', '1'), ('B8B8B7', '0'), ('B8B8B6', '1'), ('B9B8B7', '1'), ('BABAB9', '0'), ('BABABA', '0'), ('B9BAB9', '1'), ('BCBDBB', '1'), ('BABAB8', '1'), ('D2D2CF', '0'), ('C6C5C3', '1'), ('8F8F8D', '1'), ('565757', '1'), ('434445', '0'), ('32373A', '0'), ('1E1F20', '0'), ('1C1B1C', '0'), ('1A1A1A', '0'), ('171819', '1'), ('161618', '1'), ('151516', '00'), ('151415', '0'), ('141414', '010')),
    (('0D0D0D', '0'), ('0E0E0E', '0'), ('0F0F0F', '0'), ('111111', '0'), ('181818', '0'), ('242424', '0'), ('3C3D3D', '0'), ('9B9B9A', '0'), ('DBDCDB', '1'), ('8A8B8A', '0'), ('454646', '1'), ('434343', '1'), ('484848', '0'), ('4B4B4B', '1'), ('4D4D4D', '0'), ('504F4F', '0'), ('525151', '0'), ('515151', '01'), ('525252', '0'), ('505050', '0'), ('4F4F4F', '1'), ('4E4E4E', '0'), ('4E4E4D', '0'), ('4F4F4D', '1'), ('4F4F4E', '0'), ('4E4E4D', '0'), ('4D4D4D', '1'), ('4D4D4C', '1'), ('4E4E4D', '1'), ('50504E', '0'), ('555453', '0'), ('575654', '0'), ('61605E', '0'), ('969593', '0'), ('CCCDCB', '1'), ('A5A7A7', '0'), ('4B4D4E', '0'), ('303233', '0'), ('2B2C2E', '1'), ('27282A', '1'), ('232426', '0'), ('1F2123', '0'), ('1D1D1F', '1'), ('1A1A1C', '1'), ('181819', '1'), ('161617', '1'), ('151515', '001')),
    (('0D0D0C', '1'), ('0E0E0E', '1'), ('101010', '1'), ('131313', '1'), ('1C1C1C', '1'), ('2D2D2D', '1'), ('737372', '0'), ('D7D7D5', '1'), ('979897', '0'), ('656565', '0'), ('373736', '0'), ('2B2C2A', '1'), ('2A2A29', '0'), ('2D2D2B', '0'), ('393837', '0'), ('424040', '0'), ('454544', '1'), ('464646', '0'), ('464545', '0'), ('444444', '0'), ('434242', '0'), ('373535', '1'), ('2E2E2D', '1'), ('2B2B2A', '1'), ('292828', '1'), ('282727', '1'), ('272626', '11'), ('272725', '0'), ('2B2B29', '0'), ('30302E', '1'), ('3C3C3A', '0'), ('6C6C6A', '0'), ('B9BAB7', '0'), ('D7D7D5', '0'), ('AAAAA8', '0'), ('6E6E6D', '0'), ('5F6060', '1'), ('868787', '1'), ('868888', '1'), ('757779', '1'), ('4C4F50', '0'), ('313334', '1'), ('292B2C', '1'), ('222425', '0'), ('1D1E1F', '1'), ('1A191A', '1'), ('171717', '1'), ('161616', '0'), ('151515', '1')),
    (('0D0D0D', '0'), ('0E0E0E', '0'), ('101010', '1'), ('131313', '1'), ('1A1A1A', '1'), ('262626', '0'), ('444444', '1'), ('9E9F9E', '0'), ('9A9A99', '1'), ('4B4C4B', '1'), ('393836', '0'), ('373735', '1'), ('4B4B49', '1'), ('9FA09E', '0'), ('BFBFBD', '1'), ('BFBEBC', '1'), ('C0C0BE', '0'), ('C1C1BF', '0'), ('C2C2BF', '0'), ('C4C3C1', '0'), ('C5C4C2', '0'), ('959491', '1'), ('8D8C88', '0'), ('52524F', '1'), ('2D2D2C', '1'), ('2A292A', '1'), ('292929', '1'), ('2B2B2A', '0'), ('2F302E', '0'), ('3D3C3B', '0'), ('6A6A68', '1'), ('B5B6B4', '1'), ('CDCDCB', '1'), ('959493', '1'), ('5D5C5A', '1'), ('504F4C', '1'), ('7C7B78', '1'), ('C5C5C3', '1'), ('D1D1CF', '0'), ('ABABAB', '1'), ('B2B3B3', '1'), ('C5C6C5', '0'), ('818588', '0'), ('414345', '0'), ('2F3032', '0'), ('242627', '0'), ('1D1E1F', '0'), ('1A1A1A', '0'), ('171717', '1'), ('161616', '1')),
    (('0D0D0D', '1'), ('0E0E0E', '1'), ('101010', '0'), ('121212', '1'), ('161615', '0'), ('1D1D1C', '0'), ('2A2A2A', '1'), ('5E5E5C', '1'), ('B3B3B2', '0'), ('C0C0BF', '0'), ('838280', '0'), ('565452', '1'), ('5D5C59', '1'), ('C5C4C2', '1'), ('D9D8D5', '1'), ('82807D', '0'), ('737270', '1'), ('71706E', '0'), ('757472', '1'), ('959491', '1'), ('D0CFCC', '1'), ('DDDDDA', '1'), ('A3A3A0', '0'), ('4D4C4A', '1'), ('363534', '1'), ('323130', '0'), ('333331', '1'), ('3F3E3C', '1'), ('6B6B69', '0'), ('B4B4B2', '0'), ('CFCECC', '1'), ('A09F9D', '1'), ('5B5B58', '0'), ('50504D', '0'), ('747573', '1'), ('7A7B78', '1'), ('6C6D6A', '0'), ('696967', '1'), ('4E4E4E', '0'), ('505151', '1'), ('7B7C7C', '1'), ('9E9E9D', '1'), ('DCDDDD', '0'), ('92979B', '1'), ('414445', '1'), ('2E3032', '0'), ('232425', '0'), ('1D1D1D', '0'), ('191919', '1'), ('171717', '1')),
    (('0D0D0D', '0'), ('0E0E0D', '0'), ('0F100F', '0'), ('111111', '1'), ('131312', '1'), ('161615', '0'), ('1C1C1C', '1'), ('262624', '1'), ('3B3B39', '1'), ('767675', '1'), ('BEBEBC', '1'), ('C6C6C4', '0'), ('A4A3A0', '1'), ('CCCCCA', '1'), ('BDBDB9', '0'), ('6D6C69', '1'), ('52504E', '1'), ('6A6967', '1'), ('B0AFAD', '1'), ('DBDBD8', '0'), ('B1B1AE', '0'), ('6A6967', '0'), ('454442', '1'), ('3D3B3A', '0'), ('3C3B3A', '1'), ('464543', '0'), ('70706D', '0'), ('B8B8B5', '1'), ('D0D0CE', '0'), ('959593', '1'), ('545452', '1'), ('3E3D3B', '0'), ('403E3D', '0'), ('5B5A56', '1'), ('A5A5A1', '0'), ('D9D9D7', '0'), ('B9BCBC', '0'), ('545555', '1'), ('3E3D3D', '0'), ('3C3C3C', '0'), ('4D4E4F', '0'), ('888888', '1'), ('AAAAA9', '1'), ('DDE1E2', '0'), ('64696B', '0'), ('363739', '1'), ('282929', '0'), ('1F1F1F', '1'), ('1A1A1A', '1'), ('181818', '1')),
    (('0D0E0D', '1'), ('0E0E0D', '0'), ('0F0F0F', '0'), ('0F0F10', '1'), ('111111', '0'), ('131412', '0'), ('161614', '1'), ('1A1A18', '1'), ('20211F', '0'), ('292927', '1'), ('3E3E3C', '1'), ('6F6F6D', '1'), ('939290', '0'), ('8E8E8B', '0'), ('6F6E6B', '0'), ('7A7875', '1'), ('B4B3B0', '0'), ('D8D8D5', '0'), ('B5B4B2', '0'), ('6D6C6A', '0'), ('454543', '1'), ('3C3B3A', '1'), ('3D3B3A', '0'), ('474745', '1'), ('737270', '1'), ('BCBBB8', '0'), ('DADBD8', '1'), ('A3A3A1', '0'), ('5B5B59', '0'), ('42403F', '1'), ('3F3E3C', '11'), ('434240', '0'), ('4C4C49', '0'), ('6C6B68', '0'), ('BBBBB7', '1'), ('F0F1EF', '0'), ('6E706F', '0'), ('3B3C3B', '0'), ('393A3A', '0'), ('414343', '1'), ('797A7A', '1'), ('9E9F9E', '0'), ('E7E8E8', '0'), ('767B7C', '1'), ('3A3C3D', '0'), ('2A2B2D', '1'), ('202020', '0'), ('1B1B1B', '0'), ('181818', '0')),
    (('0E0E0E', '00'), ('0F0F0D', '1'), ('0F100F', '1'), ('111111', '0'), ('131311', '1'), ('151513', '1'), ('171716', '0'), ('1B1B19', '1'), ('20211F', '1'), ('282826', '0'), ('302F2D', '0'), ('3E3D3B', '0'), ('62615F', '0'), ('A9A9A7', '1'), ('DDDEDB', '0'), ('B9B9B6', '1'), ('706F6D', '0'), ('474542', '1'), ('3B3B39', '1'), ('3C3B39', '0'), ('484745', '1'), ('747370', '0'), ('BCBBB9', '1'), ('DDDDDA', '1'), ('ACACA9', '1'), ('6C6B68', '1'), ('575654', '0'), ('72716E', '1'), ('9C9C9A', '0'), ('A6A6A4', '1'), ('9E9E9C', '1'), ('9F9F9E', '1'), ('A5A5A3', '1'), ('BABAB8', '1'), ('D3D3D1', '1'), ('9C9C9A', '1'), ('474746', '0'), ('383837', '0'), ('393A39', '1'), ('4A4C4C', '0'), ('858584', '1'), ('B8B9B8', '1'), ('D0D1CF', '1'), ('585B5C', '0'), ('36383A', '0'), ('28292A', '1'), ('1F1F1F', '0'), ('1B1B1B', '1'), ('181818', '0')),
    (('0F0F0F', '010'), ('101010', '1'), ('121212', '1'), ('141413', '1'), ('161614', '1'), ('1A1A19', '0'), ('1F201E', '0'), ('282826', '0'), ('363533', '1'), ('5B5A58', '1'), ('A4A4A2', '1'), ('D8D8D6', '0'), ('B9BAB7', '0'), ('70706E', '1'), ('464543', '0'), ('3B3A38', '1'), ('3C3A39', '0'), ('474743', '0'), ('737370', '1'), ('BBBBB9', '1'), ('D5D5D2', '0'), ('A4A4A1', '1'), ('6C6A68', '0'), ('5C5B58', '0'), ('7E7C7A', '0'), ('BBBAB8', '0'), ('DADAD8', '0'), ('B0B0AE', '0'), ('8F8D8C', '0'), ('91908E', '1'), ('929190', '1'), ('888887', '0'), ('757573', '1'), ('595957', '0'), ('3D3D3C', '1'), ('383838', '0'), ('3A3A3A', '1'), ('4A4A4A', '0'), ('7B7D7C', '1'), ('B1B1B0', '0'), ('D9D9D7', '1'), ('7B7B7B', '1'), ('3F4142', '0'), ('2E3031', '1'), ('232425', '0'), ('1D1D1D', '1'), ('1A1A1A', '1'), ('171717', '0')),
    (('0F0F0F', '1'), ('101010', '00'), ('121211', '0'), ('141414', '0'), ('171716', '1'), ('1D1D1B', '1'), ('242523', '0'), ('31312F', '0'), ('565654', '1'), ('A1A19F', '0'), ('D8D8D5', '0'), ('BABAB7', '1'), ('72716F', '0'), ('454442', '0'), ('393836', '1'), ('3B3A39', '0'), ('484845', '1'), ('737370', '0'), ('BCBDBA', '1'), ('D8D9D7', '1'), ('A0A09E', '0'), ('5F5E5C', '0'), ('464543', '1'), ('474544', '0'), ('585755', '0'), ('B9B9B7', '1'), ('F8F9F7', '1'), ('A2A19F', '0'), ('5C5A58', '1'), ('474544', '1'), ('3C3B39', '1'), ('363634', '1'), ('323231', '1'), ('30302F', '1'), ('313131', '0'), ('373737', '0'), ('464646', '1'), ('696A69', '0'), ('9C9D9C', '0'), ('C8C9C7', '0'), ('C6C7C5', '0'), ('747574', '1'), ('3E3F40', '1'), ('2F3132', '1'), ('252728', '0'), ('1F2020', '1'), ('1B1B1B', '1'), ('181818', '0'), ('171716', '1')),
    (('101010', '11'), ('121212', '0'), ('151514', '1'), ('191917', '0'), ('222120', '0'), ('2E2D2C', '0'), ('51514F', '1'), ('9E9E9C', '1'), ('D6D6D5', '0'), ('B8B9B7', '0'), ('71706D', '0'), ('43413F', '1'), ('373634', '1'), ('383735', '0'), ('464543', '0'), ('737371', '1'), ('BBBBB9', '1'), ('DBDBDA', '1'), ('AAAAA8', '1'), ('636361', '0'), ('454342', '1'), ('3E3C3B', '1'), ('3B3A38', '1'), ('3C3A39', '1'), ('42403F', '0'), ('555352', '0'), ('7D7C79', '1'), ('9F9E9A', '1'), ('969693', '1'), ('71716E', '1'), ('4A4947', '0'), ('3A3A3A', '0'), ('353535', '1'), ('313131', '00'), ('3E3E3E', '1'), ('70706E', '1'), ('B4B5B3', '1'), ('C0C1C0', '0'), ('858786', '0'), ('525353', '0'), ('3A3B3C', '1'), ('303133', '1'), ('29292A', '1'), ('232324', '0'), ('1E1E1E', '1'), ('1B1B1B', '0'), ('191919', '1'), ('171717', '1')),
    (('111110', '0'), ('121212', '0'), ('151513', '0'), ('191A18', '0'), ('252523', '1'), ('393939', '0'), ('7F7F7E', '1'), ('D0D0CD', '0'), ('B9B9B7', '0'), ('6B6B69', '1'), ('3B3A38', '1'), ('2E2D2B', '1'), ('2D2C2A', '1'), ('363534', '0'), ('656562', '0'), ('B8B8B6', '1'), ('DAD9D6', '0'), ('B8B8B5', '0'), ('848482', '0'), ('6A6867', '1'), ('646361', '1'), ('61605E', '0'), ('5E5E5C', '0'), ('5E5D5B', '1'), ('5C5C5B', '1'), ('5C5B5A', '0'), ('595856', '1'), ('504E4C', '1'), ('5A5955', '1'), ('A3A2A0', '0'), ('E0E0DE', '0'), ('C0C0BE', '0'), ('767675', '1'), ('4F4E4E', '1'), ('40403F', '0'), ('3B3B3B', '1'), ('404040', '0'), ('5A5A59', '0'), ('949492', '0'), ('CECFCE', '0'), ('A9AAAB', '1'), ('686A6A', '1'), ('424445', '1'), ('353637', '1'), ('2D2D2D', '1'), ('262626', '1'), ('212222', '1'), ('1E1E1E', '0'), ('1C1C1C', '1'), ('1A1A1A', '1')),
    (('121211', '1'), ('141414', '1'), ('191918', '1'), ('242522', '1'), ('393938', '0'), ('888886', '1'), ('E5E5E3', '1'), ('939390', '1'), ('424240', '1'), ('2B2A28', '0'), ('242422', '1'), ('222321', '0'), ('252523', '0'), ('302F2E', '0'), ('7D7C79', '1'), ('A2A19E', '0'), ('767470', '0'), ('ACABA9', '1'), ('C1C1BF', '0'), ('C3C3C1', '0'), ('C2C2C0', '0'), ('C1C0BF', '1'), ('C0C0BE', '1'), ('C0C0BF', '00'), ('C1C1C0', '0'), ('C6C6C4', '1'), ('C4C4C2', '0'), ('929290', '0'), ('666563', '1'), ('737270', '1'), ('B2B2B0', '0'), ('DEDFDD', '1'), ('C0C1C0', '1'), ('7A7A7A', '1'), ('51514F', '0'), ('444342', '0'), ('404040', '0'), ('494949', '1'), ('707170', '0'), ('BABAB8', '0'), ('DBDBDA', '0'), ('A8AAAB', '0'), ('626465', '1'), ('3F4141', '1'), ('313333', '0'), ('292A2B', '1'), ('232426', '1'), ('1F2022', '1'), ('1C1D1D', '0')),
    (('131311', '1'), ('171716', '1'), ('212120', '0'), ('363634', '1'), ('7A7A78', '1'), ('E9E9E7', '0'), ('ACABA8', '1'), ('4E4D4B', '1'), ('2F2D2C', '1'), ('252422', '1'), ('222220', '00'), ('232421', '1'), ('262624', '01'), ('292827', '0'), ('343332', '1'), ('434342', '1'), ('464443', '1'), ('4A4847', '1'), ('4C4A49', '1'), ('4C4B49', '1'), ('4E4C4A', '0'), ('4E4D4C', '0'), ('504E4D', '1'), ('545251', '1'), ('62615F', '1'), ('949391', '1'), ('D5D5D3', '0'), ('D2D2D0', '1'), ('929290', '0'), ('656462', '1'), ('767573', '0'), ('B3B3B1', '1'), ('DCDCDB', '0'), ('BBBBBA', '0'), ('797A79', '1'), ('535351', '0'), ('444444', '1'), ('424242', '0'), ('4F504F', '1'), ('7C7C7B', '0'), ('C1C2C0', '1'), ('DCDCDC', '1'), ('A4A6A6', '1'), ('5E6061', '0'), ('3B3D3E', '0'), ('2E3031', '1'), ('252628', '0'), ('1F2022', '0')),
    (('131210', '1'), ('181816', '1'), ('242422', '1'), ('52524F', '1'), ('DEDEDB', '1'), ('C1C0BE', '1'), ('605E5B', '1'), ('413F3C', '0'), ('393736', '1'), ('383735', '0'), ('393836', '1'), ('3B3938', '0'), ('3C3C3A', '1'), ('3D3D3B', '1'), ('3E3E3C', '1'), ('3F3F3D', '1'), ('424140', '1'), ('444342', '0'), ('474644', '0'), ('484746', '0'), ('4A4947', '11'), ('4B4948', '0'), ('4C4B49', '0'), ('4E4C4B', '0'), ('51504E', '0'), ('555451', '0'), ('595755', '0'), ('6C6A67', '0'), ('A5A3A1', '0'), ('DEDFDD', '1'), ('C4C4C3', '1'), ('706F6D', '0'), ('565453', '1'), ('6D6C6A', '1'), ('B8B8B6', '1'), ('E5E6E5', '0'), ('B3B4B3', '1'), ('6A6B6B', '1'), ('595958', '0'), ('555555', '1'), ('5C5C5C', '0'), ('6E6F6F', '1'), ('989A9A', '1'), ('CBCCCB', '1'), ('CFD0D0', '1'), ('7B7F80', '0'), ('3B3E42', '1'), ('27292C', '0'), ('1F2123', '0')),
    (('11110F', '0'), ('141311', '0'), ('1F1E1C', '0'), ('555450', '0'), ('656461', '0'), ('464541', '1'), ('7E7D7A', '0'), ('C5C4C1', '1'), ('ADACAB', '0'), ('B3B3B1', '1'), ('B0AFAE', '0'), ('B2B0AF', '1'), ('B3B2B1', '0'), ('B4B3B3', '1'), ('B6B5B5', '0'), ('B8B7B6', '00'), ('B9B9B8', '1'), ('BABAB9', '1'), ('BABAB8', '01'), ('B9B9B8', '10'), ('BAB9B8', '1'), ('B9B9B8', '1'), ('BBBBBA', '01'), ('BBBBB9', '0'), ('C9C8C7', '1'), ('BDBCBB', '0'), ('817F7C', '0'), ('7E7D7A', '0'), ('666664', '1'), ('474745', '1'), ('383737', '0'), ('414140', '1'), ('5B5B5A', '1'), ('757676', '1'), ('7A7D7E', '1'), ('A3A4A4', '0'), ('B5B6B5', '0'), ('C6C6C5', '0'), ('D6D7D7', '0'), ('BFC0C1', '1'), ('B3B4B5', '0'), ('B5B7B9', '1'), ('7F878C', '0'), ('41474C', '0'), ('222528', '0'), ('1C1E21', '0')),
    (('0E0D0C', '1'), ('0E0E0D', '1'), ('131312', '1'), ('191816', '1'), ('161513', '0'), ('22211F', '1'), ('30302E', '0'), ('4E4E4D', '11'), ('515151', '1'), ('545453', '0'), ('565656', '1'), ('575757', '0'), ('595959', '1'), ('5B5C5B', '1'), ('5E5F5E', '1'), ('5F5F5F', '1'), ('606060', '1'), ('616261', '1'), ('626261', '0'), ('626160', '1'), ('616161', '0'), ('616262', '1'), ('616161', '1'), ('616160', '0'), ('60605F', '1'), ('5F5F5F', '1'), ('5C5D5C', '0'), ('5E5E5D', '1'), ('4F4F4F', '1'), ('313130', '1'), ('282827', '1'), ('282828', '1'), ('232323', '0'), ('212121', '0'), ('202020', '10'), ('232323', '1'), ('2D2E2D', '0'), ('434444', '0'), ('545555', '0'), ('5F5F5F', '1'), ('636463', '0'), ('5A5B5C', '1'), ('535556', '1'), ('464849', '0'), ('2F3134', '0'), ('212224', '0'), ('1C1C1E', '1'), ('18191B', '1')),
    (('0C0C0C', '0'), ('0D0D0D', '0'), ('0E0E0E', '0'), ('0F0F0E', '0'), ('101010', '0'), ('111111', '0'), ('111211', '0'), ('111110', '0'), ('131312', '1'), ('141514', '0'), ('151514', '1'), ('151515', '1'), ('161616', '00'), ('161717', '0'), ('171717', '0'), ('181818', '0'), ('191919', '0'), ('191918', '1'), ('1A1A19', '0'), ('1A1A1A', '110'), ('1A1A1B', '0'), ('1A1A1A', '0'), ('1A1A19', '010'), ('181818', '10'), ('191919', '10'), ('181818', '01'), ('171717', '1010'), ('181818', '00000'), ('1A1A1A', '0'), ('191919', '0'), ('181818', '1'), ('181817', '0'), ('171717', '0'), ('161616', '1'), ('151516', '0')),
    (('0C0C0C', '00'), ('0D0D0D', '0'), ('0E0E0D', '1'), ('0E0E0E', '1'), ('0F0F0F', '0'), ('0F1010', '0'), ('101010', '00'), ('111111', '01'), ('121211', '1'), ('121212', '01'), ('131313', '100'), ('131413', '0'), ('141413', '1'), ('141414', '111'), ('151515', '1'), ('151514', '1'), ('141414', '1'), ('151515', '0'), ('141414', '1'), ('141415', '0'), ('151515', '1100'), ('141414', '110'), ('141413', '1'), ('141414', '1011110'), ('151515', '11'), ('141514', '0'), ('141414', '0'), ('131313', '001')),
)
LOGO_WIDTH = 50
LOGO_HEIGHT = 22


HOME = Path.home()
BIN_DIR = HOME / ".local/bin"
INSTALLED_SCRIPT = BIN_DIR / APP_NAME

CONFIG_HOME = HOME / ".config"
SYSTEMD_DIR = CONFIG_HOME / "systemd/user"
RYOKU_CONFIG = CONFIG_HOME / "ryoku/ryogami.json"
WE_CONFIG = CONFIG_HOME / "we-layerd/config.toml"

STATE_FILE = HOME / ".local/state/ryoku-wallpaper"
DATA_DIR = HOME / ".local/share/ryoku-we"
BACKUP_ROOT = DATA_DIR / "backups"

ACTIVE_BACKDROP = HOME / ".config/quickshell/shell/modules/wallpaper/Backdrop.qml"
SOURCE_BACKDROP = HOME / ".local/share/ryoku/rashin/source/quickshell/shell/modules/wallpaper/Backdrop.qml"

ACTIVE_SHELL = HOME / ".config/quickshell/shell/shell.qml"
SOURCE_SHELL = HOME / ".local/share/ryoku/rashin/source/quickshell/shell/shell.qml"

GIF_SERVICE = SYSTEMD_DIR / "ryoku-gif-wallpaper-patch.service"
GIF_PATH = SYSTEMD_DIR / "ryoku-gif-wallpaper-patch.path"
SYNC_SERVICE = SYSTEMD_DIR / "ryoku-we-sync.service"
SYNC_PATH = SYSTEMD_DIR / "ryoku-we-sync.path"
INDEX_SERVICE = SYSTEMD_DIR / "ryoku-we-index.service"
INDEX_PATH = SYSTEMD_DIR / "ryoku-we-index.path"
WE_SERVICE = SYSTEMD_DIR / "we-layerd.service"

SYNTHETIC_DIR = HOME / "Pictures/Wallpapers/Wallpaper Engine"
DEFAULT_VIDEO_ROOT = HOME / "videowalls"

OLD_HELPERS = [
    HOME / ".local/bin/ryoku-we-sync",
    HOME / ".local/bin/ryoku-wallpaper-support",
]


def say(msg: str = "") -> None:
    print(msg, flush=True)


def run(cmd, *, check=False, capture=False, quiet=False, timeout=None):
    kwargs = {}
    if capture:
        kwargs["stdout"] = subprocess.PIPE
        kwargs["stderr"] = subprocess.STDOUT
        kwargs["text"] = True
    elif quiet:
        kwargs["stdout"] = subprocess.DEVNULL
        kwargs["stderr"] = subprocess.DEVNULL

    try:
        return subprocess.run(
            [str(x) for x in cmd],
            check=check,
            timeout=timeout,
            **kwargs,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None


def systemctl(*args, quiet=True):
    return run(["systemctl", "--user", *args], quiet=quiet)


def command_path(name: str) -> str | None:
    p = shutil.which(name)
    if p:
        return p
    candidate = BIN_DIR / name
    if candidate.exists():
        return str(candidate)
    return None


def timestamp() -> str:
    return datetime.now().strftime("%Y%m%d-%H%M%S")


def unit_state(unit: str) -> tuple[str, str]:
    active = run(["systemctl", "--user", "is-active", unit], capture=True)
    enabled = run(["systemctl", "--user", "is-enabled", unit], capture=True)
    a = active.stdout.strip() if active and active.stdout else "unknown"
    e = enabled.stdout.strip() if enabled and enabled.stdout else "unknown"
    return a, e


def service_active(name: str) -> bool:
    result = run(["systemctl", "--user", "is-active", "--quiet", name])
    return bool(result and result.returncode == 0)


def backup(paths: list[Path]) -> Path:
    dest = BACKUP_ROOT / timestamp()
    dest.mkdir(parents=True, exist_ok=True)

    copied = 0
    for p in paths:
        if not p.exists() or not p.is_file():
            continue

        try:
            rel = p.relative_to(HOME)
        except ValueError:
            rel = Path(p.name)

        out = dest / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(p, out)
        copied += 1

    if copied:
        say(f"[backup] {copied} file(s) -> {dest}")
    else:
        say("[backup] nothing needed backing up")

    return dest


def steam_root() -> Path | None:
    candidates = [
        HOME / ".local/share/Steam",
        HOME / ".steam/steam",
        HOME / ".var/app/com.valvesoftware.Steam/.local/share/Steam",
    ]

    seen = set()
    for candidate in candidates:
        try:
            resolved = candidate.resolve()
        except Exception:
            resolved = candidate

        key = str(resolved)
        if key in seen:
            continue
        seen.add(key)

        if (resolved / "steamapps").is_dir():
            return resolved

    return None


def workshop_root() -> Path | None:
    root = steam_root()
    if not root:
        return None
    return root / "steamapps/workshop/content/431960"


def we_assets_root() -> Path | None:
    root = steam_root()
    if not root:
        return None
    return root / "steamapps/common/wallpaper_engine/assets"


def parse_we_muted() -> bool | None:
    if not WE_CONFIG.exists():
        return None

    section = ""
    try:
        for line in WE_CONFIG.read_text().splitlines():
            stripped = line.strip()

            if stripped.startswith("[") and stripped.endswith("]"):
                section = stripped
                continue

            if section == "[renderer]" and stripped.startswith("muted ="):
                value = stripped.split("=", 1)[1].strip().lower()
                return value in ("true", "1", "yes", "on")
    except Exception:
        pass

    return None


def parse_ryogami_muted() -> bool | None:
    if not RYOKU_CONFIG.exists():
        return None

    try:
        data = json.loads(RYOKU_CONFIG.read_text())
        if "wallpaperMute" in data:
            return bool(data["wallpaperMute"])
    except Exception:
        pass

    return None


def audio_muted(default: bool = True) -> bool:
    we_value = parse_we_muted()
    if we_value is not None:
        return we_value

    ryoku_value = parse_ryogami_muted()
    if ryoku_value is not None:
        return ryoku_value

    return default


def write_we_audio(muted: bool) -> None:
    WE_CONFIG.parent.mkdir(parents=True, exist_ok=True)

    if not WE_CONFIG.exists():
        ensure_we_config(muted=muted)
        return

    lines = WE_CONFIG.read_text().splitlines()
    out = []
    section = ""
    saw_muted = False
    saw_volume = False

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("[") and stripped.endswith("]"):
            section = stripped

        if section == "[renderer]" and stripped.startswith("muted ="):
            out.append(f"muted = {'true' if muted else 'false'}")
            saw_muted = True
            continue

        if section == "[renderer]" and stripped.startswith("volume ="):
            out.append(f"volume = {'0.0' if muted else '1.0'}")
            saw_volume = True
            continue

        out.append(line)

    rebuilt = []
    current = ""
    inserted = False

    for line in out:
        stripped = line.strip()

        if stripped.startswith("[") and stripped.endswith("]"):
            if current == "[renderer]" and not inserted:
                if not saw_volume:
                    rebuilt.append(f"volume = {'0.0' if muted else '1.0'}")
                if not saw_muted:
                    rebuilt.append(f"muted = {'true' if muted else 'false'}")
                inserted = True

            current = stripped

        rebuilt.append(line)

    if current == "[renderer]" and not inserted:
        if not saw_volume:
            rebuilt.append(f"volume = {'0.0' if muted else '1.0'}")
        if not saw_muted:
            rebuilt.append(f"muted = {'true' if muted else 'false'}")

    WE_CONFIG.write_text("\n".join(rebuilt) + "\n")


def write_ryogami_audio(muted: bool) -> None:
    if not RYOKU_CONFIG.exists():
        return

    try:
        data = json.loads(RYOKU_CONFIG.read_text())
    except Exception as exc:
        say(f"[warn] Could not parse {RYOKU_CONFIG}: {exc}")
        return

    data["wallpaperMute"] = bool(muted)
    RYOKU_CONFIG.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def set_audio_muted(muted: bool, *, apply_now: bool = True) -> int:
    write_we_audio(muted)
    write_ryogami_audio(muted)

    say("Wallpaper audio: " + ("MUTED" if muted else "UNMUTED"))

    if not apply_now:
        return 0

    if service_active("we-layerd.service"):
        systemctl("restart", "we-layerd.service")

    if service_active("ryogami.service"):
        systemctl("restart", "ryogami.service")
        time.sleep(0.7)

    sync()
    return 0


def toggle_audio() -> int:
    return set_audio_muted(not audio_muted())


def ensure_ryogami_config(*, muted: bool) -> None:
    if not RYOKU_CONFIG.exists():
        say(f"[warn] Ryogami config not found: {RYOKU_CONFIG}")
        return

    try:
        data = json.loads(RYOKU_CONFIG.read_text())
    except Exception as exc:
        say(f"[warn] Could not parse {RYOKU_CONFIG}: {exc}")
        return

    data.setdefault("features", {})["steam"] = True
    data["wallpaperMute"] = bool(muted)

    RYOKU_CONFIG.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    say(
        "[ok] Ryogami Steam support enabled; wallpaper audio "
        + ("muted" if muted else "unmuted")
    )


def ensure_we_config(*, muted: bool) -> None:
    assets = we_assets_root()
    assets_text = str(assets) if assets else ""

    WE_CONFIG.parent.mkdir(parents=True, exist_ok=True)

    if not WE_CONFIG.exists():
        WE_CONFIG.write_text(
            f"""[general]
interactive = false
show_fps = false
scale_mode = "cover"

[renderer]
library_path = ""
source = ""
assets_path = "{assets_text}"
cache_path = "~/.cache/we-layerd/renderer"
prefer_dmabuf = true
allow_shm_fallback = true
fps = 60
max_fps = 60
speed = 1.0
volume = {"0.0" if muted else "1.0"}
muted = {"true" if muted else "false"}
msaa_samples = 1
fill_mode = "cover"
rotation_degrees = 0

[integrations]
media = true
audio_spectrum = false
audio_source = "@DEFAULT_MONITOR@"
audio_sample_rate = 48000
audio_update_hz = 30
"""
        )
        say(f"[created] {WE_CONFIG}")
        return

    lines = WE_CONFIG.read_text().splitlines()
    out = []
    section = ""

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("[") and stripped.endswith("]"):
            section = stripped

        if section == "[renderer]" and stripped.startswith("assets_path =") and assets_text:
            out.append(f'assets_path = "{assets_text}"')
            continue

        out.append(line)

    WE_CONFIG.write_text("\n".join(out) + "\n")
    write_we_audio(muted)

    say(
        "[ok] we-layerd configured; wallpaper audio "
        + ("muted" if muted else "unmuted")
    )


def patch_gif_file(path: Path) -> bool:
    if not path.exists():
        say(f"[skip] missing GIF target: {path}")
        return False

    s = path.read_text()
    original = s

    anchor = "    function fillModeFor(img) {"
    helper = (
        "    function isGifSource(s) {\n"
        '        return /\\.gif(?:\\?|$)/i.test(String(s || ""));\n'
        "    }\n\n"
        "    function fillModeFor(img) {"
    )

    if "function isGifSource(s)" not in s:
        if anchor not in s:
            say(f"[warn] GIF patch anchor missing: {path}")
            return False
        s = s.replace(anchor, helper, 1)

    for ident in ("imgA", "imgB"):
        old = "    Image {\n        id: " + ident + "\n"
        new = "    AnimatedImage {\n        id: " + ident + "\n"

        if old in s:
            s = s.replace(old, new, 1)

    for ident in ("imgA", "imgB"):
        pos = s.find("id: " + ident)

        if pos == -1:
            continue

        nearby = s[pos : pos + 500]

        if "playing: view.isGifSource(source)" not in nearby:
            old = (
                "        id: " + ident + "\n"
                "        anchors.fill: parent\n"
                "        cache: false\n"
                "        asynchronous: true\n"
            )

            if old in s:
                s = s.replace(
                    old,
                    old + "        playing: view.isGifSource(source)\n",
                    1,
                )

    s = s.replace(
        "        id: srcA\n"
        "        sourceItem: imgA\n"
        "        hideSource: true\n"
        "        live: false",
        "        id: srcA\n"
        "        sourceItem: imgA\n"
        "        hideSource: true\n"
        "        live: view.isGifSource(imgA.source)",
        1,
    )

    s = s.replace(
        "        id: srcB\n"
        "        sourceItem: imgB\n"
        "        hideSource: true\n"
        "        live: false",
        "        id: srcB\n"
        "        sourceItem: imgB\n"
        "        hideSource: true\n"
        "        live: view.isGifSource(imgB.source)",
        1,
    )

    if s != original:
        path.write_text(s)
        say(f"[patched] GIF support: {path}")
        return True

    say(f"[ok] GIF support already present: {path}")
    return False


def gif_patch() -> int:
    for target in (ACTIVE_BACKDROP, SOURCE_BACKDROP):
        patch_gif_file(target)
    return 0


def restore_native_live_rule(path: Path) -> None:
    if not path.exists():
        return

    s = path.read_text()
    original = s

    patterns = [
        r'wallpaperLive:\s*wallpaper\.live\s*\|\|\s*wallpaper\.wallpaperPath\.indexOf\("/Wallpaper Engine/"\)\s*!==\s*-1',
        r'wallpaperLive:\s*wallpaper\.live\s*\|\|\s*\(wallpaper\.wallpaperPath\.indexOf\("/Wallpaper Engine/"\)\s*!==\s*-1\s*&&\s*wallpaper\.wallpaperPath\.indexOf\("\[scene\]"\)\s*!==\s*-1\)',
    ]

    for pat in patterns:
        s = re.sub(pat, "wallpaperLive: wallpaper.live", s)

    if s != original:
        path.write_text(s)
        say(f"[restored] native wallpaperLive rule: {path}")


def configured_video_root() -> Path:
    """Return stable Ryogami's video wallpaper root (paths.videoWallpaper)."""
    if RYOKU_CONFIG.is_file():
        try:
            data = json.loads(RYOKU_CONFIG.read_text(errors="replace"))
            raw = str((data.get("paths") or {}).get("videoWallpaper") or "").strip()
            if raw:
                return Path(os.path.expandvars(os.path.expanduser(raw)))
        except Exception:
            pass
    return DEFAULT_VIDEO_ROOT


def video_index_dir() -> Path:
    return configured_video_root() / "Wallpaper Engine"


def _same_generated_index(path: Path, base: Path) -> bool:
    try:
        path.absolute().relative_to(base.absolute())
        return True
    except Exception:
        return False


def hardlink_or_reflink(source: Path, output: Path) -> bool:
    """Expose a large media file without making an ordinary full copy."""
    try:
        os.link(source, output)
        return True
    except FileExistsError:
        return True
    except OSError:
        pass

    # Cross-filesystem fallback for CoW filesystems (btrfs/xfs/reflink-capable).
    cp = command_path("cp") or "/usr/bin/cp"
    result = run([cp, "--reflink=always", "--", source, output], quiet=True, timeout=120)
    return bool(result and result.returncode == 0 and output.is_file())


def safe_index_title(value: str, fallback: str) -> str:
    title = str(value or fallback)
    title = re.sub(r"[^\w .()\-]+", "_", title).strip()
    return (title or fallback)[:90]


def project_media_file(source: Path, data: dict) -> Path | None:
    rel = str(data.get("file") or "").strip()
    if not rel:
        return None
    candidate = source / rel
    if not candidate.is_file():
        return None
    if candidate.suffix.lower() not in {
        ".mp4", ".webm", ".mkv", ".mov", ".m4v",
        ".jpg", ".jpeg", ".png", ".webp", ".gif",
    }:
        return None
    return candidate


def project_preview_file(source: Path, data: dict, *, allow_gif: bool = True) -> Path | None:
    candidates = []
    preview = str(data.get("preview") or "").strip()
    if preview:
        candidates.append(source / preview)

    # Prefer static previews so stable Ryogami does not try to transcode a GIF
    # merely because a Wallpaper Engine scene was selected from the index.
    candidates.extend([
        source / "preview.jpg",
        source / "preview.jpeg",
        source / "preview.png",
        source / "preview.webp",
    ])
    if allow_gif:
        candidates.append(source / "preview.gif")

    seen = set()
    for candidate in candidates:
        key = str(candidate)
        if key in seen:
            continue
        seen.add(key)
        if not candidate.is_file():
            continue
        if not allow_gif and candidate.suffix.lower() == ".gif":
            continue
        if candidate.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp", ".gif"}:
            return candidate
    return None


def make_scene_thumbnail(source: Path, data: dict, output_base: Path) -> Path | None:
    static = project_preview_file(source, data, allow_gif=False)
    if static is not None:
        output = output_base.with_suffix(static.suffix.lower())
        try:
            os.link(static, output)
            return output
        except OSError:
            # Scene previews are small enough to copy when Steam and Pictures
            # live on different filesystems. Never copy full Workshop videos.
            try:
                shutil.copy2(static, output)
                return output
            except OSError:
                pass

    animated = project_preview_file(source, data, allow_gif=True)
    if animated is None:
        return None

    # If only an animated preview exists, extract one still for the picker.
    # The real scene remains in Steam and is rendered by we-layerd.
    output = output_base.with_suffix(".jpg")
    ffmpeg = command_path("ffmpeg")
    if not ffmpeg:
        return None
    result = run([
        ffmpeg, "-loglevel", "error", "-y", "-i", animated,
        "-frames:v", "1", "-q:v", "3", output,
    ], quiet=True, timeout=30)
    return output if result and result.returncode == 0 and output.is_file() else None


def build_workshop_index() -> int:
    root = workshop_root()
    if not root or not root.is_dir():
        say("[warn] Wallpaper Engine Workshop directory not found; index unchanged")
        return 1

    picture_dir = SYNTHETIC_DIR
    video_dir = video_index_dir()
    picture_dir.mkdir(parents=True, exist_ok=True)
    video_dir.mkdir(parents=True, exist_ok=True)

    # Stable Ryogami scans stills/scenes from paths.wallpaper and videos from
    # paths.videoWallpaper. Keep matching "Wallpaper Engine" subfolders in both
    # roots so the picker can present the same logical collection.
    for generated_dir in (picture_dir, video_dir):
        for entry in generated_dir.iterdir():
            if entry.is_file() or entry.is_symlink():
                try:
                    entry.unlink()
                except OSError as exc:
                    say(f"[warn] Could not remove stale index entry {entry.name}: {exc}")

    indexed = 0
    scenes = 0
    videos = 0
    others = 0
    skipped = 0

    for source in sorted(root.iterdir()):
        if not source.is_dir() or not source.name.isdigit():
            continue

        data = read_project(source)
        if not data:
            skipped += 1
            continue

        wid = source.name
        kind = project_type(source)
        title = safe_index_title(data.get("title"), wid)

        if kind == "scene":
            out_base = picture_dir / f"{wid} - {title} [scene]"
            if make_scene_thumbnail(source, data, out_base) is not None:
                indexed += 1
                scenes += 1
            else:
                skipped += 1
            continue

        media = project_media_file(source, data)

        if kind == "video":
            if media is None or media.suffix.lower() not in {".mp4", ".webm", ".mkv", ".mov", ".m4v"}:
                skipped += 1
                say(f"[warn] Workshop {wid} is video but its media file is missing/unsupported")
                continue

            out = video_dir / f"{wid} - {title} [video]{media.suffix.lower()}"
            if hardlink_or_reflink(media, out):
                indexed += 1
                videos += 1
            else:
                say(f"[warn] Could not hardlink/reflink Workshop video {wid}; skipped to avoid duplicating a large file")
                skipped += 1
            continue

        # Non-video/non-scene projects get a picker-safe still entry when possible.
        if media is None or media.suffix.lower() in {".mp4", ".webm", ".mkv", ".mov", ".m4v"}:
            media = project_preview_file(source, data, allow_gif=False)
        if media is None:
            skipped += 1
            continue

        out = picture_dir / f"{wid} - {title} [{kind}]{media.suffix.lower()}"
        try:
            os.link(media, out)
        except FileExistsError:
            pass
        except OSError:
            try:
                shutil.copy2(media, out)
            except OSError as exc:
                say(f"[warn] Could not index Workshop {wid}: {exc}")
                skipped += 1
                continue

        indexed += 1
        others += 1

    say(f"[ok] Wallpaper Engine index: {indexed} entries ({scenes} scene, {videos} video, {others} other, {skipped} skipped)")
    say(f"[ok] Scene/still picker folder: {picture_dir}")
    say(f"[ok] Video picker folder:       {video_dir}")
    return 0


def apply_scene_live_rule(path: Path) -> None:
    if not path.exists():
        return

    s = path.read_text()
    original = s
    desired = (
        'wallpaperLive: wallpaper.live || '
        '(wallpaper.wallpaperPath.indexOf("/Wallpaper Engine/") !== -1 '
        '&& wallpaper.wallpaperPath.indexOf("[scene]") !== -1)'
    )

    patterns = [
        r'wallpaperLive:\s*wallpaper\.live\s*\|\|\s*wallpaper\.wallpaperPath\.indexOf\("/Wallpaper Engine/"\)\s*!==\s*-1',
        r'wallpaperLive:\s*wallpaper\.live\s*\|\|\s*\(wallpaper\.wallpaperPath\.indexOf\("/Wallpaper Engine/"\)\s*!==\s*-1\s*&&\s*wallpaper\.wallpaperPath\.indexOf\("\[scene\]"\)\s*!==\s*-1\)',
    ]

    replaced = False
    for pat in patterns:
        updated, count = re.subn(pat, desired, s, count=1)
        if count:
            s = updated
            replaced = True
            break

    if not replaced and "wallpaperLive: wallpaper.live" in s:
        s = s.replace("wallpaperLive: wallpaper.live", desired, 1)

    if s != original:
        path.write_text(s)
        say(f"[patched] scene handoff rule: {path}")
    elif desired in s:
        say(f"[ok] scene handoff rule present: {path}")


def selected_path() -> Path | None:
    if not STATE_FILE.is_file():
        return None

    value = STATE_FILE.read_text(errors="replace").strip()

    if value.startswith("file://"):
        value = value[7:]

    return Path(value) if value else None


def selected_workshop(selected: Path | None):
    root = workshop_root()

    if not selected or not root:
        return None, None

    # Native/newer Ryogami can select files directly from the Workshop tree.
    try:
        rel = selected.resolve().relative_to(root.resolve())
        if rel.parts and rel.parts[0].isdigit():
            wid = rel.parts[0]
            source = root / wid
            if source.is_dir():
                return wid, source
    except Exception:
        pass

    # Stable Ryogami uses two roots: pictures for still/scene cards and
    # paths.videoWallpaper for videos. Recover the Workshop ID from either
    # generated index filename because hardlinks do not resolve to Steam paths.
    if not (
        _same_generated_index(selected, SYNTHETIC_DIR)
        or _same_generated_index(selected, video_index_dir())
    ):
        return None, None

    match = re.match(r"^(\d+)\s+-\s+", selected.name)
    if not match:
        return None, None

    wid = match.group(1)
    source = root / wid
    return (wid, source) if source.is_dir() else (None, None)


def read_project(source: Path) -> dict:
    project = source / "project.json"

    if not project.is_file():
        return {}

    try:
        return json.loads(project.read_text(errors="replace"))
    except Exception:
        return {}


def project_type(source: Path) -> str:
    """Return a Wallpaper Engine project type, inferring it when metadata omits `type`."""
    data = read_project(source)
    kind = str(data.get("type", "")).strip().lower()
    if kind:
        return kind

    # Some Workshop uploads omit the `type` field entirely. Infer from the
    # project entry file and common Wallpaper Engine project structure instead
    # of misclassifying them as ordinary still images.
    rel = str(data.get("file", "")).strip()
    suffix = Path(rel).suffix.lower() if rel else ""
    name = Path(rel).name.lower() if rel else ""

    if name == "scene.json" or (source / "scene.json").is_file():
        return "scene"
    if suffix in {".mp4", ".webm", ".mkv", ".mov", ".m4v", ".avi"}:
        return "video"
    if suffix in {".html", ".htm"} or (source / "index.html").is_file():
        return "web"

    return "unknown"


def project_title(source: Path) -> str:
    return str(read_project(source).get("title", "")).strip()


def set_we_source(source: Path) -> None:
    if not WE_CONFIG.is_file():
        raise RuntimeError(f"Missing we-layerd config: {WE_CONFIG}")

    lines = WE_CONFIG.read_text().splitlines()
    out = []
    section = ""
    replaced = False

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("[") and stripped.endswith("]"):
            section = stripped

        if section == "[renderer]" and stripped.startswith("source ="):
            out.append(f'source = "{source}"')
            replaced = True
        else:
            out.append(line)

    if not replaced:
        raise RuntimeError(f"renderer.source missing from {WE_CONFIG}")

    WE_CONFIG.write_text("\n".join(out) + "\n")


def kill_native_scene(source: Path) -> None:
    needle = str(source)

    for proc in Path("/proc").iterdir():
        if not proc.name.isdigit():
            continue

        try:
            cmd = (
                (proc / "cmdline")
                .read_bytes()
                .replace(b"\0", b" ")
                .decode(errors="replace")
            )
        except Exception:
            continue

        if "skwd-wall-vk" not in cmd:
            continue
        if "--scene" not in cmd:
            continue
        if needle not in cmd:
            continue

        try:
            os.kill(int(proc.name), signal.SIGTERM)
        except ProcessLookupError:
            pass


def stop_we() -> None:
    systemctl("stop", "we-layerd.service")


def sync() -> int:
    selected = selected_path()

    if selected is None:
        stop_we()
        return 0

    wid, source = selected_workshop(selected)

    if source is None:
        stop_we()
        say(f"Ryoku native: {selected}")
        return 0

    kind = project_type(source)

    say(f"Workshop: {wid}")
    say(f"Type: {kind or 'unknown'}")

    if kind != "scene":
        stop_we()
        say(f"Ryoku native Workshop renderer: {wid} {kind or 'unknown'}")
        return 0

    set_we_source(source)

    systemctl("restart", "we-layerd.service")
    time.sleep(0.7)

    if not service_active("we-layerd.service"):
        say("[error] we-layerd.service failed; native scene renderer left untouched")
        return 1

    current = selected_path()
    current_id, _ = selected_workshop(current)

    if current_id != wid:
        stop_we()
        return 0

    for _ in range(10):
        current = selected_path()
        current_id, _ = selected_workshop(current)

        if current_id != wid:
            stop_we()
            return 0

        kill_native_scene(source)
        time.sleep(0.10)

    say(f"Wallpaper Engine scene -> we-layerd: {wid}")
    say(f"Source: {source}")
    return 0


def write_units() -> None:
    we_layerd = command_path("we-layerd")

    if not we_layerd:
        raise SystemExit("we-layerd was not found. Install/build we-layerd first.")

    SYSTEMD_DIR.mkdir(parents=True, exist_ok=True)

    WE_SERVICE.write_text(
        f"""[Unit]
Description=Wallpaper Engine renderer via we-layerd
After=graphical-session.target

[Service]
Type=simple
ExecStart={we_layerd} run --config %h/.config/we-layerd/config.toml
Restart=on-failure
RestartSec=1
"""
    )

    GIF_SERVICE.write_text(
        f"""[Unit]
Description=Reapply Ryoku GIF wallpaper support

[Service]
Type=oneshot
ExecStart=%h/.local/bin/{APP_NAME} gif-patch

[Install]
WantedBy=default.target
"""
    )

    GIF_PATH.write_text(
        """[Unit]
Description=Watch Ryoku wallpaper renderer for updates

[Path]
PathChanged=%h/.config/quickshell/shell/modules/wallpaper/Backdrop.qml
Unit=ryoku-gif-wallpaper-patch.service

[Install]
WantedBy=default.target
"""
    )

    SYNC_SERVICE.write_text(
        f"""[Unit]
Description=Route Ryoku Wallpaper Engine scenes through we-layerd
After=ryogami.service

[Service]
Type=oneshot
ExecStart=%h/.local/bin/{APP_NAME} sync

[Install]
WantedBy=default.target
"""
    )

    SYNC_PATH.write_text(
        """[Unit]
Description=Watch Ryoku wallpaper selection for Wallpaper Engine scenes

[Path]
PathChanged=%h/.local/state/ryoku-wallpaper
Unit=ryoku-we-sync.service

[Install]
WantedBy=default.target
"""
    )

    workshop = workshop_root()
    if workshop:
        acf = workshop.parent.parent / "appworkshop_431960.acf"
        INDEX_SERVICE.write_text(
            f"""[Unit]
Description=Refresh Ryoku-WE Wallpaper Engine picker index

[Service]
Type=oneshot
ExecStartPre=/usr/bin/sleep 2
ExecStart=%h/.local/bin/{APP_NAME} index
"""
        )
        INDEX_PATH.write_text(
            f"""[Unit]
Description=Watch Steam Wallpaper Engine subscriptions

[Path]
PathChanged={workshop}
PathChanged={acf}
Unit=ryoku-we-index.service

[Install]
WantedBy=default.target
"""
        )

    say("[ok] systemd user units written")


def install_self() -> None:
    BIN_DIR.mkdir(parents=True, exist_ok=True)

    current = Path(__file__).resolve()

    if current != INSTALLED_SCRIPT:
        shutil.copy2(current, INSTALLED_SCRIPT)

    INSTALLED_SCRIPT.chmod(0o755)

    alias = BIN_DIR / "ryoku-we"
    try:
        if alias.exists() or alias.is_symlink():
            alias.unlink()
        alias.symlink_to(INSTALLED_SCRIPT.name)
    except OSError:
        pass

    say(f"[installed] {INSTALLED_SCRIPT}")


def install() -> int:
    say(f"{APP_NAME} v{VERSION}")
    say()

    if not command_path("ryoku"):
        raise SystemExit("ryoku was not found in PATH.")
    if not command_path("ryogami"):
        raise SystemExit("ryogami was not found in PATH.")
    if not command_path("we-layerd"):
        raise SystemExit("we-layerd was not found in PATH or ~/.local/bin.")

    root = steam_root()
    say(f"[ok] Steam root: {root}" if root else "[warn] Steam root not detected")

    current_mute = audio_muted(default=True)

    backup(
        [
            ACTIVE_BACKDROP,
            SOURCE_BACKDROP,
            ACTIVE_SHELL,
            SOURCE_SHELL,
            RYOKU_CONFIG,
            WE_CONFIG,
            GIF_SERVICE,
            GIF_PATH,
            SYNC_SERVICE,
            SYNC_PATH,
            INDEX_SERVICE,
            INDEX_PATH,
            WE_SERVICE,
            *OLD_HELPERS,
        ]
    )

    install_self()

    systemctl("disable", "--now", "ryoku-we-sync.path")
    systemctl("disable", "--now", "ryoku-we-index.path")
    systemctl("disable", "--now", "ryoku-gif-wallpaper-patch.path")

    apply_scene_live_rule(ACTIVE_SHELL)
    apply_scene_live_rule(SOURCE_SHELL)

    ensure_ryogami_config(muted=current_mute)
    ensure_we_config(muted=current_mute)
    gif_patch()
    build_workshop_index()
    write_units()

    systemctl("daemon-reload")
    systemctl("enable", "--now", "ryoku-gif-wallpaper-patch.service")
    systemctl("enable", "--now", "ryoku-gif-wallpaper-patch.path")
    systemctl("enable", "ryoku-we-sync.service")
    systemctl("enable", "--now", "ryoku-we-sync.path")
    if INDEX_PATH.exists():
        systemctl("enable", "ryoku-we-index.service")
        systemctl("enable", "--now", "ryoku-we-index.path")

    if command_path("ryoku"):
        run(["ryoku", "reload"], quiet=True)
        time.sleep(1.5)

    sync()

    say()
    say("Installed.")
    say("  Pictures            -> native Ryoku")
    say("  GIFs                -> native Ryoku AnimatedImage")
    say("  Local videos        -> native Ryoku")
    say(f"  Workshop scenes     -> {SYNTHETIC_DIR}")
    say(f"  Workshop videos     -> {video_index_dir()}")
    say("  Video renderer      -> native Ryoku")
    say("  Scene renderer      -> we-layerd")
    say("  Wallpaper audio     -> " + ("MUTED" if current_mute else "UNMUTED"))
    say()
    say(f"Launch TUI with: {APP_NAME}")
    return 0


def restart_we() -> int:
    selected = selected_path()
    wid, source = selected_workshop(selected)

    if not source or project_type(source) != "scene":
        say("Current wallpaper is not a Wallpaper Engine scene.")
        return 0

    set_we_source(source)
    systemctl("restart", "we-layerd.service")
    time.sleep(0.7)

    if service_active("we-layerd.service"):
        for _ in range(6):
            kill_native_scene(source)
            time.sleep(0.1)
        say("we-layerd restarted.")
        return 0

    say("[error] we-layerd failed to restart.")
    return 1


def open_picker() -> int:
    result = run(["ryogami", "wallpaper", "ui"], quiet=True)

    if result is None:
        say("[error] Could not launch Ryogami wallpaper picker.")
        return 1

    return result.returncode


def uninstall() -> int:
    say("Disabling Ryoku-WE automation...")

    for unit in (
        "ryoku-we-sync.path",
        "ryoku-we-sync.service",
        "ryoku-we-index.path",
        "ryoku-we-index.service",
        "ryoku-gif-wallpaper-patch.path",
        "ryoku-gif-wallpaper-patch.service",
    ):
        systemctl("disable", "--now", unit)

    systemctl("stop", "we-layerd.service")

    for p in (SYNC_PATH, SYNC_SERVICE, INDEX_PATH, INDEX_SERVICE, GIF_PATH, GIF_SERVICE, WE_SERVICE):
        try:
            p.unlink()
            say(f"[removed] {p}")
        except FileNotFoundError:
            pass

    systemctl("daemon-reload")

    say()
    say("Automation removed.")
    say("The current GIF QML patch and backups were intentionally kept.")
    say(f"Backups: {BACKUP_ROOT}")
    return 0


def status_dict() -> dict:
    selected = selected_path()
    wid, source = selected_workshop(selected)

    info = {
        "selected": str(selected) if selected else "<none>",
        "workshop_id": wid or "",
        "project_type": "",
        "project_title": "",
        "muted": audio_muted(default=True),
        "route": "Native Ryoku",
        "units": {},
        "renderers": [],
        "ryoku_version": "",
    }

    if source:
        info["project_type"] = project_type(source)
        info["project_title"] = project_title(source)

        if info["project_type"] == "scene":
            info["route"] = "we-layerd" if service_active("we-layerd.service") else "scene pending/native"
        else:
            info["route"] = "Native Ryoku"

    if command_path("ryoku"):
        r = run(["ryoku", "--version"], capture=True)
        if r and r.stdout:
            info["ryoku_version"] = r.stdout.strip()

    for unit in (
        "ryoku-gif-wallpaper-patch.path",
        "ryoku-we-sync.path",
        "ryoku-we-index.path",
        "we-layerd.service",
        "ryogami.service",
        "ryoku-shell.service",
    ):
        info["units"][unit] = unit_state(unit)

    proc = run(
        ["pgrep", "-a", "-f", "skwd-wall-vk|skwd-paper-v2|we-layerd"],
        capture=True,
    )

    if proc and proc.returncode == 0 and proc.stdout:
        info["renderers"] = [line for line in proc.stdout.splitlines() if line.strip()]

    return info


def status() -> int:
    info = status_dict()

    say(f"{APP_NAME} v{VERSION}")

    if info["ryoku_version"]:
        say(f"Ryoku: {info['ryoku_version']}")

    say(f"Wallpaper audio: {'MUTED' if info['muted'] else 'UNMUTED'}")
    say(f"Selected: {info['selected']}")

    if info["workshop_id"]:
        say(f"Workshop ID: {info['workshop_id']}")
        say(f"Title: {info['project_title'] or '<unknown>'}")
        say(f"Project type: {info['project_type'] or 'unknown'}")

    say(f"Route: {info['route']}")
    say()

    for unit, (active, enabled) in info["units"].items():
        say(f"{unit}: active={active}, enabled={enabled}")

    say()

    if WE_CONFIG.exists():
        section = ""
        for line in WE_CONFIG.read_text().splitlines():
            stripped = line.strip()

            if stripped.startswith("[") and stripped.endswith("]"):
                section = stripped

            if section == "[renderer]" and stripped.startswith(("source =", "volume =", "muted =")):
                say("we-layerd " + stripped)

    say()

    if info["renderers"]:
        say("Renderers:")
        for line in info["renderers"]:
            say(line)
    else:
        say("Renderers: none")

    return 0



def _logo_plain_lines() -> list[str]:
    return ["".join(text for _color, text in row) for row in LOGO_ROWS]


def _rgb(hex_color: str) -> tuple[int, int, int]:
    return (
        int(hex_color[0:2], 16),
        int(hex_color[2:4], 16),
        int(hex_color[4:6], 16),
    )


def _luminance(hex_color: str) -> float:
    r, g, b = _rgb(hex_color)
    return (0.2126 * r) + (0.7152 * g) + (0.0722 * b)


def _xterm_gray_index(hex_color: str) -> int:
    # xterm grayscale ramp 232..255 corresponds roughly to RGB 8..238.
    lum = _luminance(hex_color)
    shade = round((lum - 8.0) / 10.0)
    return max(0, min(23, shade)) + 232


def print_logo() -> int:
    """
    Print the uploaded logo using its original per-segment RGB values.
    Truecolor terminals get the exact HTML colors; 256-color terminals get
    the closest xterm grayscale shade.
    """
    if not sys.stdout.isatty() or os.environ.get("TERM", "") == "dumb":
        print("\n".join(_logo_plain_lines()))
        return 0

    colorterm = os.environ.get("COLORTERM", "").lower()
    truecolor = "truecolor" in colorterm or "24bit" in colorterm
    reset = "\033[0m"

    for row in LOGO_ROWS:
        rendered = []

        for hex_color, text in row:
            if truecolor:
                r, g, b = _rgb(hex_color)
                rendered.append(f"\033[38;2;{r};{g};{b}m{text}")
            else:
                rendered.append(f"\033[38;5;{_xterm_gray_index(hex_color)}m{text}")

        rendered.append(reset)
        print("".join(rendered))

    return 0



def capture_action(func, *args, **kwargs) -> tuple[int, str]:
    buf = io.StringIO()

    try:
        with contextlib.redirect_stdout(buf), contextlib.redirect_stderr(buf):
            rc = func(*args, **kwargs)

        if rc is None:
            rc = 0

        return int(rc), buf.getvalue().strip()
    except SystemExit as exc:
        code = exc.code if isinstance(exc.code, int) else 1
        if exc.code and not isinstance(exc.code, int):
            print(exc.code, file=buf)
        return code, buf.getvalue().strip()
    except Exception as exc:
        return 1, (buf.getvalue() + f"\n{type(exc).__name__}: {exc}").strip()


def tui_addstr(stdscr, y, x, text, attr=0):
    h, w = stdscr.getmaxyx()

    if y < 0 or y >= h or x >= w:
        return

    max_len = max(0, w - x - 1)

    try:
        stdscr.addnstr(y, x, str(text), max_len, attr)
    except curses.error:
        pass


def modal(stdscr, title: str, body: str) -> None:
    while True:
        stdscr.erase()
        h, w = stdscr.getmaxyx()

        tui_addstr(stdscr, 1, 2, f"{APP_NAME} — {title}", curses.A_BOLD)

        body_lines = []
        width = max(20, w - 6)

        for raw in (body or "(no output)").splitlines():
            wrapped = textwrap.wrap(raw, width=width) or [""]
            body_lines.extend(wrapped)

        max_body = max(1, h - 6)
        shown = body_lines[-max_body:]

        for i, line in enumerate(shown):
            tui_addstr(stdscr, 3 + i, 3, line)

        tui_addstr(stdscr, h - 2, 2, "Press Enter / Esc / q to return", curses.A_DIM)
        stdscr.refresh()

        key = stdscr.getch()

        if key in (10, 13, 27, ord("q"), ord("Q")):
            return


def confirm(stdscr, prompt: str) -> bool:
    stdscr.erase()
    tui_addstr(stdscr, 2, 2, APP_NAME, curses.A_BOLD)
    tui_addstr(stdscr, 4, 4, prompt)
    tui_addstr(stdscr, 6, 4, "Press y to confirm, anything else to cancel.", curses.A_DIM)
    stdscr.refresh()
    return stdscr.getch() in (ord("y"), ord("Y"))


def draw_tui(stdscr, selected_index: int):
    info = status_dict()
    muted = info["muted"]

    menu = [
        ("picker", "Open Ryoku wallpaper picker", open_picker),
        ("mute", "Unmute wallpaper audio" if muted else "Mute wallpaper audio", toggle_audio),
        ("sync", "Sync current wallpaper / renderer", sync),
        ("index", "Refresh Wallpaper Engine picker index", build_workshop_index),
        ("gif", "Reapply GIF support", gif_patch),
        ("we", "Restart Wallpaper Engine renderer", restart_we),
        ("repair", "Install / repair Ryoku-WE support", install),
        ("status", "Detailed status", status),
        ("logo", "Show Ryoku-WE logo", lambda: 0),
        ("uninstall", "Uninstall automation", uninstall),
        ("quit", "Quit", lambda: 0),
    ]

    stdscr.erase()
    h, w = stdscr.getmaxyx()

    if h < 25 or w < 72:
        tui_addstr(stdscr, 1, 2, f"{APP_NAME} needs roughly 72x20 terminal space.", curses.A_BOLD)
        tui_addstr(stdscr, 3, 2, "Resize the terminal, or use CLI commands such as:")
        tui_addstr(stdscr, 5, 4, f"{APP_NAME} status")
        tui_addstr(stdscr, 6, 4, f"{APP_NAME} toggle-mute")
        tui_addstr(stdscr, 7, 4, f"{APP_NAME} repair")
        return menu

    title = f" {APP_NAME} "
    tui_addstr(stdscr, 1, 2, "═" * (w - 4), curses.A_DIM)
    tui_addstr(stdscr, 1, max(3, (w - len(title)) // 2), title, curses.A_BOLD)
    tui_addstr(stdscr, 2, 3, f"Unified Ryoku + Wallpaper Engine support  v{VERSION}", curses.A_DIM)

    audio_text = "MUTED" if muted else "UNMUTED"
    route = info["route"]
    selected = info["project_title"] or Path(info["selected"]).name or info["selected"]

    tui_addstr(stdscr, 4, 4, "Wallpaper audio :", curses.A_BOLD)
    tui_addstr(stdscr, 4, 22, audio_text)

    tui_addstr(stdscr, 5, 4, "Current route   :", curses.A_BOLD)
    tui_addstr(stdscr, 5, 22, route)

    tui_addstr(stdscr, 6, 4, "Selected        :", curses.A_BOLD)
    tui_addstr(stdscr, 6, 22, selected)

    if info["workshop_id"]:
        meta = f"Workshop {info['workshop_id']}  [{info['project_type'] or 'unknown'}]"
        tui_addstr(stdscr, 7, 22, meta, curses.A_DIM)

    we_active = info["units"]["we-layerd.service"][0]
    gif_watch = info["units"]["ryoku-gif-wallpaper-patch.path"][0]
    sync_watch = info["units"]["ryoku-we-sync.path"][0]

    tui_addstr(stdscr, 9, 4, f"we-layerd: {we_active}", curses.A_DIM)
    tui_addstr(stdscr, 9, 26, f"GIF watcher: {gif_watch}", curses.A_DIM)
    tui_addstr(stdscr, 9, 50, f"Router: {sync_watch}", curses.A_DIM)

    tui_addstr(stdscr, 11, 4, "Actions", curses.A_BOLD)

    start_y = 12
    for i, (_, label, _) in enumerate(menu):
        attr = curses.A_REVERSE | curses.A_BOLD if i == selected_index else 0
        prefix = "▶ " if i == selected_index else "  "
        tui_addstr(stdscr, start_y + i, 6, prefix + label, attr)

    footer = "↑/↓ navigate   Enter select   m mute/unmute   s sync   r repair   q quit"
    tui_addstr(stdscr, h - 2, 3, footer, curses.A_DIM)

    return menu





def tui(stdscr) -> int:
    curses.curs_set(0)
    stdscr.keypad(True)
    stdscr.timeout(1000)

    # Startup logo.
    logo_splash(stdscr, wait_for_key=False)

    index = 0

    while True:
        menu = draw_tui(stdscr, index)
        stdscr.refresh()

        key = stdscr.getch()

        # Timeout is intentional so status information refreshes automatically.
        if key == -1:
            continue

        if key in (ord("q"), ord("Q")):
            return 0

        if key in (curses.KEY_UP, ord("k")):
            index = (index - 1) % len(menu)
            continue

        if key in (curses.KEY_DOWN, ord("j")):
            index = (index + 1) % len(menu)
            continue

        if key in (ord("m"), ord("M")):
            rc, out = capture_action(toggle_audio)
            modal(stdscr, "Audio toggle", out or f"Exit code: {rc}")
            continue

        if key in (ord("s"), ord("S")):
            rc, out = capture_action(sync)
            modal(stdscr, "Sync", out or f"Exit code: {rc}")
            continue

        if key in (ord("r"), ord("R")):
            rc, out = capture_action(install)
            modal(stdscr, "Install / repair", out or f"Exit code: {rc}")
            continue

        if key not in (10, 13):
            continue

        key_name, label, func = menu[index]

        if key_name == "quit":
            return 0

        if key_name == "uninstall":
            if not confirm(stdscr, "Disable and remove Ryoku-WE automation?"):
                continue

        if key_name == "picker":
            # Ryogami opens its own UI; no modal is needed.
            capture_action(open_picker)
            continue

        if key_name == "logo":
            logo_splash(stdscr, wait_for_key=True)
            continue

        rc, out = capture_action(func)
        modal(stdscr, label, out or f"Exit code: {rc}")


def logo_splash(stdscr, *, wait_for_key: bool = False) -> None:
    """
    Render the uploaded 50x22 binary logo using its original grayscale/RGB
    brightness. On 256-color terminals this maps to the xterm 24-step gray ramp.
    """
    stdscr.erase()
    h, w = stdscr.getmaxyx()

    pair_for_shade = {}
    use_256 = False

    try:
        if curses.has_colors():
            curses.start_color()
            try:
                curses.use_default_colors()
            except curses.error:
                pass

            # 24 grayscale foreground colors, one pair per xterm gray.
            if getattr(curses, "COLORS", 0) >= 256 and getattr(curses, "COLOR_PAIRS", 0) >= 25:
                use_256 = True
                for shade in range(24):
                    pair = shade + 1
                    curses.init_pair(pair, 232 + shade, -1)
                    pair_for_shade[shade] = curses.color_pair(pair)
    except curses.error:
        use_256 = False

    if h >= LOGO_HEIGHT + 2 and w >= LOGO_WIDTH + 4:
        start_y = max(0, (h - LOGO_HEIGHT) // 2)
        start_x = max(1, (w - LOGO_WIDTH) // 2)

        for row_index, row in enumerate(LOGO_ROWS):
            x = start_x

            for hex_color, text in row:
                lum = _luminance(hex_color)

                if use_256:
                    shade = _xterm_gray_index(hex_color) - 232
                    attr = pair_for_shade.get(shade, 0)
                else:
                    # Graceful fallback for basic-color terminals.
                    if lum < 55:
                        attr = curses.A_DIM
                    elif lum < 150:
                        attr = curses.A_NORMAL
                    else:
                        attr = curses.A_BOLD

                try:
                    stdscr.addstr(start_y + row_index, x, text, attr)
                except curses.error:
                    pass

                x += len(text)

        stdscr.refresh()

        if wait_for_key:
            stdscr.timeout(-1)
            stdscr.getch()
            stdscr.timeout(1000)
        else:
            # Let the exact logo be visible briefly before the main TUI.
            stdscr.timeout(950)
            stdscr.getch()
            stdscr.timeout(1000)
        return

    title = f"{APP_NAME}  v{VERSION}"
    hint = "Enlarge the terminal to display the full 50x22 logo."
    tui_addstr(stdscr, max(1, h // 2 - 1), max(1, (w - len(title)) // 2), title, curses.A_BOLD)
    tui_addstr(stdscr, max(2, h // 2 + 1), max(1, (w - len(hint)) // 2), hint, curses.A_DIM)
    stdscr.refresh()

    if wait_for_key:
        stdscr.timeout(-1)
        stdscr.getch()
        stdscr.timeout(1000)
    else:
        time.sleep(0.6)



def launch_tui() -> int:
    if not sys.stdin.isatty() or not sys.stdout.isatty():
        say(f"{APP_NAME}: TUI requires a terminal.")
        say(f"Try: {APP_NAME} status")
        return 1

    try:
        return curses.wrapper(tui)
    except KeyboardInterrupt:
        return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        prog=APP_NAME,
        description="TUI + automation for Ryoku GIF/video/Wallpaper Engine support",
    )

    parser.add_argument(
        "command",
        nargs="?",
        default="tui",
        choices=[
            "tui",
            "install",
            "repair",
            "status",
            "sync",
            "index",
            "gif-patch",
            "mute",
            "unmute",
            "toggle-mute",
            "restart-we",
            "picker",
            "logo",
            "uninstall",
        ],
    )

    args = parser.parse_args()

    if args.command == "tui":
        return launch_tui()
    if args.command in ("install", "repair"):
        return install()
    if args.command == "status":
        return status()
    if args.command == "sync":
        return sync()
    if args.command == "index":
        return build_workshop_index()
    if args.command == "gif-patch":
        return gif_patch()
    if args.command == "mute":
        return set_audio_muted(True)
    if args.command == "unmute":
        return set_audio_muted(False)
    if args.command == "toggle-mute":
        return toggle_audio()
    if args.command == "restart-we":
        return restart_we()
    if args.command == "picker":
        return open_picker()
    if args.command == "logo":
        return print_logo()
    if args.command == "uninstall":
        return uninstall()

    return 1


if __name__ == "__main__":
    raise SystemExit(main())
